#!/usr/bin/env bash
#
# Copyright 2020 Chi-kwan Chan
# Copyright 2020 Steward Observatory
#
# Licensed under the Apache License, Version 2.0 (the "License"); you
# may not use this file except in compliance with the License.  You
# may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.  See the License for the specific language governing
# permissions and limitations under the License.

cmd="$(basename "$0")"

# We consider 3 cases here:
case "$cmd" in
	# 1. This script is run by `jupyter [subcmd [args ...]]`.
	jupyter)
		sub="$1"
		shift
		;;
	# 2. This script is symlinked and run by `jupyter-subcmd [args ...]`
	jupyter-*)
		sub="${cmd#jupyter-}"
		;;
	# 3. This script is symlinked and run by `subcmd [args ...]`
	*)
		sub="$cmd"
		;;
esac

case "$sub" in
	notebook)
		if [ ! -f .jupyter/jupyter_notebook_config.py ] && [ $# -eq 0 ] ; then
		    set -- '--allow-root' '--ip=0.0.0.0' '--no-browser'
		fi
		;;
	nbconvert | console)
		;;
	'')
		echo "No subcommand; do nothing"
		exit 0
		;;
	*)
		echo "Unknown subcommand \"$sub\"; do nothing"
		exit 1
		;;
esac

python3 -m "$sub" "$@"
