#!/usr/bin/env bash

if [ x$(uname) == x"Darwin" ]; then
	IP=$(ifconfig | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p')
	SS=$(echo $DISPLAY | sed -En 's/.*:(.*)/\1/p')
	xhost + $IP
	CONNECTX="-e DISPLAY=$IP:$SS"
	echo "Darwin: tunnel X11 to $IP:$SS"
else
	CONNECTX="-e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix"
	echo "Linux: connect X11 socket \$DISPLAY=$DISPLAY"
fi

mkdir -p workdir &&
docker run --rm -it $CONNECTX \
	-v $PWD/repository:/repository:ro \
	-v $PWD/workdir:/home/calibrator/data \
	chanchikwan/hops
